name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verificar se o index.html existe
        run: |
          if [ ! -f public/index.html ]; then
            echo "index.html não encontrado!"
            exit 1
            fi
          
         deploy:
            runs-on: ubuntu-latest
            needs: validate
            steps:
              - name: Checkout
                uses: actions/checkout@v2

              - name: Deploy para Github Pages
                uses: peaceiris/actions-gh-page@v3
              with:
                github_token: &{{ secrets.GITHUB_TOKEN }}
                public_dir: ./public
